# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.PositiveIntegerField()),
                ('Quantity', models.PositiveIntegerField()),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsDiscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=255)),
                ('discription', models.TextField()),
                ('specification', models.TextField()),
                ('photos', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='ProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductsDiscription'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('UserId', 'ProductId')]),
        ),
    ]
