# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='key',
        ),
        migrations.AlterField(
            model_name='cart',
            name='ProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductsDiscription'),
        ),
    ]
