# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180323_1856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('UserId', 'ProductId')]),
        ),
    ]
