# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_cores', models.PositiveIntegerField()),
                ('speed', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Whole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mrp', models.FloatField()),
                ('price', models.FloatField()),
                ('photos', models.URLField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ram',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productdescription.Whole'),
        ),
        migrations.AddField(
            model_name='processor',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productdescription.Whole'),
        ),
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productdescription.Whole'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('userid', 'productid')]),
        ),
    ]
